export const WHATSAPP_NUMBER = '971504308516'

export const RIBBON = [
  'Flight bookings',
  'Golden Visa',
  'Mainland & free zone setup',
  'Emirates ID',
  'Holiday packages',
  'Family sponsorship',
  'Trade licence renewal',
  'Document clearing',
]

export const SERVICES = [
  {
    key: 'travel',
    num: '01',
    title: 'Travel & Tours',
    lead: 'Flights, hotels, holiday packages and tour coordination.',
    headline: 'Holidays and business trips, booked end to end.',
    body: 'From a single flight to a full family holiday, we coordinate flights, hotels, transfers and tours through trusted tourism partners — one itinerary, one price, one person to call if plans change.',
    icon: ['M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z'],
    optionLabel: 'What are you planning?',
    messageLabel: 'Travel dates & preferences',
    messagePlaceholder: 'e.g. 2 adults, Georgia, 12–18 Nov, 4-star hotel',
    formTitle: 'Plan a trip',
    note: 'For visa-on-arrival destinations, a passport copy is usually enough to quote.',
    baseDocs: [['passport', 'Passport copy (all travellers)']],
    options: [
      { key: 'flights', label: 'Flight bookings', docs: [] },
      { key: 'hotels', label: 'Hotel reservations', docs: [['dates', 'Preferred dates & city (any format)']] },
      { key: 'packages', label: 'Holiday packages', docs: [['visa', 'UAE visa / Emirates ID copy']] },
      { key: 'tours', label: 'Tour coordination', docs: [['group', 'Group list with passport numbers']] },
    ],
  },
  {
    key: 'visa',
    num: '02',
    title: 'Visa Assistance',
    lead: 'Tourist, visit, digital nomad, family sponsorship and Golden Visa.',
    headline: 'The right visa, filed right the first time.',
    body: 'We check eligibility, prepare the file and follow the application through to approval — tourist and visit visas, digital nomad permits, family sponsorship and Golden Visa nominations for investors, professionals and talent.',
    icon: ['M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z', 'M14 2v4a2 2 0 0 0 2 2h4', 'M12 18a3 3 0 1 0 0-6 3 3 0 0 0 0 6'],
    optionLabel: 'Visa type',
    messageLabel: 'Tell us about your situation',
    messagePlaceholder: 'e.g. Sponsoring my wife and two children, employment visa holder',
    formTitle: 'Apply for a visa',
    note: 'Passport must be valid for at least six months. Originals may be requested at a later stage.',
    baseDocs: [['passport', 'Passport copy (6+ months validity)'], ['photo', 'Passport-size photo, white background']],
    options: [
      { key: 'tourist', label: 'Tourist / visit visa', docs: [['ticket', 'Return ticket or travel plan']] },
      { key: 'nomad', label: 'Digital nomad visa', docs: [['employment', 'Employment contract or business proof'], ['income', 'Bank statements (3 months, income ≥ USD 3,500/mo)'], ['insurance', 'UAE health insurance']] },
      { key: 'family', label: 'Family sponsorship', docs: [['sponsorEid', 'Sponsor Emirates ID & visa'], ['salary', 'Salary certificate or labour contract'], ['tenancy', 'Attested tenancy contract (Ejari)'], ['relation', 'Attested marriage / birth certificate']] },
      { key: 'golden', label: 'Golden Visa', docs: [['eligibility', 'Eligibility proof (title deed, degree, investment or award)'], ['eid', 'Emirates ID (if resident)'], ['insurance', 'UAE health insurance']] },
    ],
  },
  {
    key: 'business',
    num: '03',
    title: 'Business Setup',
    lead: 'Mainland & free zone formation, trade licence issuance and renewal.',
    headline: 'Open in Dubai without the guesswork.',
    body: 'We help you choose between mainland and free zone, reserve the trade name, draft the paperwork and collect the licence — then keep it renewed year after year so the business never stalls on an expiry date.',
    icon: ['M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16', 'M2 7h20v13a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z'],
    optionLabel: 'Setup type',
    messageLabel: 'Proposed activity & trade name',
    messagePlaceholder: 'e.g. General trading, 2 shareholders, names: “Nile Star”',
    formTitle: 'Set up a company',
    note: 'Shareholders currently employed in the UAE may need an NOC from their sponsor.',
    baseDocs: [['passport', 'Passport copies of all shareholders'], ['names', 'Three proposed trade names']],
    options: [
      { key: 'mainland', label: 'Mainland company formation', docs: [['entry', 'UAE entry stamp / visa copy'], ['activity', 'Business activity description'], ['noc', 'NOC from current sponsor (if employed)']] },
      { key: 'freezone', label: 'Free zone company formation', docs: [['entry', 'UAE entry stamp / visa copy'], ['activity', 'Business activity description']] },
      { key: 'licence', label: 'Trade licence issuance', docs: [['moa', 'Memorandum of association / LSA agreement'], ['tenancy', 'Office tenancy contract (Ejari)']] },
      { key: 'renewal', label: 'Trade licence renewal', docs: [['licence', 'Current trade licence copy'], ['tenancy', 'Valid tenancy contract (Ejari)']] },
    ],
  },
  {
    key: 'pro',
    num: '04',
    title: 'Government & PRO Services',
    lead: 'Document clearing, Emirates ID, medical testing and legal coordination.',
    headline: 'Government offices, handled on your behalf.',
    body: 'Typing, submissions, follow-ups and collections across immigration, Emirates ID, medical fitness centres and other authorities — plus general legal and administrative coordination so you spend your day at work, not in a queue.',
    icon: ['M3 22h18', 'M6 18v-7', 'M10 18v-7', 'M14 18v-7', 'M18 18v-7', 'M12 2 2 7h20z'],
    optionLabel: 'Service required',
    messageLabel: 'Anything we should know?',
    messagePlaceholder: 'e.g. Visa expires on 30 Sep, need Emirates ID renewal',
    formTitle: 'Request PRO assistance',
    note: 'Timelines depend on the authority; we confirm the expected turnaround before starting.',
    baseDocs: [['passport', 'Passport copy'], ['visa', 'Current UAE visa / entry permit']],
    options: [
      { key: 'clearing', label: 'Document clearing', docs: [['documents', 'Documents to be processed or attested']] },
      { key: 'eid', label: 'Emirates ID processing', docs: [['photo', 'Passport-size photo, white background'], ['oldEid', 'Existing Emirates ID (renewal only)']] },
      { key: 'medical', label: 'Medical testing guidance', docs: [['photo', 'Passport-size photo, white background']] },
      { key: 'legal', label: 'Legal & administrative coordination', docs: [['documents', 'Relevant contracts or letters'], ['eid', 'Emirates ID copy']] },
    ],
  },
]
